/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    indexDocsSidebar: [
        {
            type: 'autogenerated',
            dirName: '.',
        },

        // {
        //     type: 'category',
        //     label: 'Docs',
        //     link: {
        //         type: 'generated-index',
        //         title: 'Doccss',
        //     },
        //     items: ['index', 'mobyd/index', 'nest/index']
        // },

        // 'index',
        // {
        //     type: "autogenerated",
        //     dirName: 'mobyd',
        // },
        // {
        //     type: "autogenerated",
        //     dirName: 'nest'
        // },

    ],

    mobydDocsSidebar: [
        {
            type: 'autogenerated',
            dirName: 'mobyd',
        },

        // 'mobyd/index',
        // {
        //     type: 'category',
        //     label: 'Mobyd Docs',
        //     items: ['mobyd/index'],
        // },
    ],

    nestDocsSidebar: [
        {
            type: 'autogenerated',
            dirName: 'nest',
        },

        // 'nest/index',
        // {
        //     type: 'category',
        //     label: 'Nest Docs',
        //     items: ['nest/index'],
        // },
    ],

};

module.exports = sidebars;
